export const metricHelp = {
  filteredDecisions: "Number of published pass decisions matching the active filters.",
  reviewCandidates: "Filtered decisions that meet the published same-frame review-queue rule.",
  sameFrameMargin: "Best same-frame Local xT v1 minus the selected receiver's same-frame Local xT v1. It is a location proxy, not a completion probability.",
  pviCoverage: "Number of filtered decisions with Local xPass and same-frame delta xT required to score the selected pass's Pass Viability Index v2.",
  medianSelectedPvi: "Median selected-pass PVI in the filtered set. PVI is a deterministic 0–100 composite, not a probability or player rating.",
  medianPviGap: "Median of frame-best PVI minus selected-pass PVI in the filtered set. Positive values indicate that another teammate scored higher under PVI.",
  medianLocalXPass: "Median Local xPass v1 of the observed passes in the filtered set: estimated completion chance conditional on attempting each pass.",
  medianAvailability: "Median Availability v1 of the observed passes in the filtered set: deterministic lane/interception feasibility, not a probability.",
  providerChoiceCoverage: "Number of filtered observed passes with complete provider Option score, xPass, and xThreat inputs. Provider-defined options are a shortlist, not every tracked teammate.",
  medianSelectedProviderChoice: "Median Provider Peak Composite Score for observed passes in the filtered set: 100 × cube root(Provider Option score × Provider xPass × Provider xThreat). It is a unitless display scale, not a probability or Local PVI.",
  selectedProviderChoiceRank: "Rank of the observed receiver by the unrounded provider product among provider-defined options available at the provider pass moment; 1 is highest. The highest alternative is labelled Best provider-defined option.",
  providerChoiceMargin: "Best provider-defined option's Provider Peak Composite Score minus the observed receiver's score. It compares provider peak-opportunity values and is not an actual-frame pass-selection verdict.",
  pviSelectionFilter: "Filters by selected-pass PVI rank: frame-best means rank 1; not frame-best means a teammate scored higher at that actual pass frame.",
  minSelectedPviFilter: "Keep decisions whose selected-pass PVI is at least this 0–100 value. Missing PVI is excluded when this filter is active.",
  maxSelectedPviFilter: "Keep decisions whose selected-pass PVI is at most this 0–100 value. Missing PVI is excluded when this filter is active.",
  minPviGapFilter: "Keep decisions where frame-best PVI minus selected-pass PVI is at least this many points. Use a positive value to find missed higher-PVI options.",
  maxPviGapFilter: "Keep decisions where frame-best PVI minus selected-pass PVI is at most this many points.",
  matchTime: "Match clock and stable decision identifier for this observed pass.",
  passer: "Player recorded as making the observed pass.",
  passerOriginThird: "Third occupied by the detected passing player at the actual pass frame, in that team’s attacking orientation. It uses equal defensive, middle, and attacking thirds of the physical pitch.",
  passerOriginSide: "Lateral third occupied by the detected passing player at the actual pass frame, in that team’s attacking orientation. Left and right are the passing team’s left and right, not fixed broadcast sides.",
  passerOriginThirdFilter: "Keep passes whose detected passer occupied the chosen defensive, middle, or attacking third at the actual pass frame. Missing passer tracking is excluded when this filter is active.",
  passerOriginSideFilter: "Keep passes whose detected passer occupied the chosen left, center, or right lateral third at the actual pass frame. Missing passer tracking is excluded when this filter is active.",
  selectedReceiver: "Teammate who actually received the observed pass.",
  bestSameFrameOption: "Teammate with the highest same-frame Local xT v1, evaluated at the actual pass frame. This is not necessarily the highest PVI option.",
  sameFrameRank: "Rank by same-frame Local xT v1 among tracked teammate candidates; 1 is highest.",
  selectedOpenXt: "Local xT v1 at the selected receiver's position at the actual pass frame.",
  bestOpenXt: "Highest Local xT v1 among tracked teammate positions at the actual pass frame.",
  selectedLocalXPass: "Local xPass v1: the project-owned estimated chance that an attempted pass to the selected teammate completes.",
  selectedAvailability: "Availability v1: project-owned lane and interception feasibility proxy for the selected pass; it is not a probability.",
  selectedPvi: "Pass Viability Index v2 for the selected pass: a deterministic 0–100 blend of Local xPass (55%) and bounded same-frame delta xT utility (45%). Availability remains visible but is not an input.",
  pviRank: "Rank by Pass Viability Index v2 among actual-frame teammate candidates; 1 is highest.",
  frameBestPvi: "Highest Pass Viability Index v2 among actual-frame teammate candidates. The sublabel identifies that teammate.",
  pviGap: "Frame-best PVI minus selected-pass PVI. A positive value means another candidate scored higher under the PVI formula; it is not a verdict on the observed choice.",
  classification: "Timing-aware comparison category between the selected pass, same-frame location values, and provider peak-opportunity data.",
  providerAgreement: "Whether the best provider-defined option and highest same-frame Local xT v1 option identify the same receiver.",
  passOutcome: "Observed provider outcome for the pass. It is execution evidence, separate from local xPass and PVI.",
  qa: "Browser-local analyst annotation. It does not modify the published data.",
  receiver: "Tracked teammate candidate at the actual pass frame.",
  order: "Pinned display order: selected option first, Highest PVI second, then remaining teammates by PVI rank.",
  locationValid: "Whether a valid tracked receiver position exists at the actual pass frame for same-frame metrics.",
  sameFrameOpenXt: "Local xT v1 (the versioned open-location xT grid) at this teammate's tracked position at the actual pass frame. It measures location value, not pass completion chance.",
  sameFrameDeltaXt: "The Local xT v1 gain from a hypothetical pass to this teammate: their same-frame value minus Local xT v1 at the actual pass origin (the ball location, or passer fallback). Negative values can represent viable retention or backward passes.",
  deltaSelected: "This teammate's same-frame Local xT v1 minus the selected receiver's same-frame Local xT v1.",
  localXPass: "Local xPass v1: the project-owned calibrated estimate of completion conditional on attempting this pass.",
  localXPassRank: "Rank by Local xPass v1 among actual-frame teammate candidates; 1 is safest by this estimator.",
  availability: "Availability v1: deterministic lane/interception feasibility derived from actual-frame geometry and tracking motion. It is not a probability.",
  localConfidence: "Input-quality category for Local xPass v1; it describes tracking support, not certainty in a single pass outcome.",
  passViability: "Pass Viability Index v2: deterministic 0–100 composite of Local xPass (55%) and bounded same-frame delta xT utility (45%). Availability is not an input. It is not a probability or a player rating.",
  pviXtUtility: "Bounded tanh transform of same-frame delta xT used inside PVI v2. Zero delta xT is 0.5; negative values remain valid but score lower.",
  providerXPass: "Provider-supplied xPass for this provider-defined option, typically measured at its provider-selected peak-opportunity frame.",
  providerXThreat: "Provider-supplied xThreat for this provider-defined option at its provider-selected peak-opportunity frame.",
  providerOptionScore: "Provider-supplied composite option score at the provider-selected peak-opportunity frame.",
  providerExpectedThreat: "Provider xPass × Provider xThreat at this option's provider-selected peak-opportunity frame. It is derived locally from two provider fields and excludes Provider Option score.",
  providerExpectedThreatRank: "Rank by Provider expected threat (Provider xPass × Provider xThreat) among provider-defined options at the provider peak-opportunity frame; 1 is highest.",
  providerChoiceObjective: "Raw source-aligned ranking product: Provider Option score × Provider xPass × Provider xThreat at this option's provider-selected peak-opportunity frame. It is retained for deterministic ranking, not displayed as a percentage.",
  providerCompositeScore: "Provider Peak Composite Score: 100 × cube root(Provider Option score × Provider xPass × Provider xThreat). It is a unitless monotonic display transform, not a probability. The unrounded raw product determines rank.",
  providerChoiceRank: "Rank by the unrounded source-aligned provider product among provider-defined options available at the actual provider pass moment; 1 is highest. The highest eligible alternative is labelled Best provider-defined option.",
  providerPeak: "Frame at which the provider recorded this option's peak opportunity; it can differ from the actual pass frame.",
  peakOffset: "Provider peak frame relative to the actual provider pass frame.",
  availableAtPass: "Provider availability flag during the pass moment window. It does not make provider peak metrics same-frame values.",
  providerSameFrame: "Whether the provider peak frame equals the actual pass frame; only then are provider metrics same-frame.",
} as const;
